settings:
  bullet: '*'
plugins:
  - remark-preset-lint-consistent
  - remark-preset-lint-markdown-style-guide
  - remark-preset-lint-recommended
  # Generate a table of contents in `## Contents`
  - - remark-toc
    - heading: contents

  - remark-frontmatter
  - - remark-lint-frontmatter-schema
    - schemas:
        types/project.schema.yaml:
          - '**/*.mdx'

  - remark-lint-blockquote-indentation
  - remark-lint-no-duplicate-headings
  - remark-lint-no-duplicate-headings-in-section

  - preset-prettier

  # - remark-preset-lint-consistent
  # - remark-preset-lint-recommended
