settings:
  bullet: '*'
plugins:
  # Check that markdown is consistent.
  - remark-preset-lint-consistent
  # Few recommended rules.
  - remark-preset-lint-recommended
  # Generate a table of contents in `## Contents`
  - - remark-toc
    - heading: contents
  - remark-frontmatter

  - - remark-lint-frontmatter-schema
    - schemas:
        types/project.schema.yaml:
          - components/projects/rocket-car/rocket-car-page.mdx
          - README.md

  # - remark-preset-lint-consistent
  # - remark-preset-lint-markdown-style-guide
  # - remark-preset-lint-recommended
