/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t public/pinecone.glb
Author: richardK (https://sketchfab.com/richardk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pinecone-9ad231a5335b453e90bda43c3d35e1a4
Title: Pinecone
*/

import * as THREE from "three";
import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group } from "three";

type GLTFResult = GLTF & {
  nodes: {
    front2_aiAmbientOcclusion1_0: THREE.Mesh;
  };
  materials: {
    aiAmbientOcclusion1: THREE.MeshStandardMaterial;
  };
};

export const PineconeModel = forwardRef<Group>(
  (props: JSX.IntrinsicElements["group"], ref) => {
    const { nodes, materials } = useGLTF(
      "/pinecone.glb"
    ) as unknown as GLTFResult;
    return (
      <group {...props} ref={ref} dispose={null}>
        <mesh
          geometry={nodes.front2_aiAmbientOcclusion1_0.geometry}
          material={materials.aiAmbientOcclusion1}
          position={[-4.38, 0, -0.04]}
        />
      </group>
    );
  }
);

useGLTF.preload("/pinecone.glb");
